# Generated by Django 3.1.1 on 2020-09-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro',
            new_name='Registros_filtrados',
        ),
    ]
